### ISSUE TITLE
弹出的窗口有需要翻墙的内容

### ISSUE THREAD

**Issue by edwinhuish** [Mapaler/GetOneDriveDirectLink#1]
弹出的窗口有需要翻墙的内容，一般没有设置全局翻墙的情况下，无法应用chrome的翻墙。

**Comment by Mapaler** [comment]
弹出的窗口是微软的，与我无关的。从你点击按钮的一刻开始，到数据返回之前，全是微软的官方SDK在操作，我无法修改的。
你可以自己添加翻墙规则，是哪些域名我也没看过
