### ISSUE TITLE
文件数量多的时候，打开无反应

### ISSUE THREAD

**Issue by zplzpl** [Mapaler/GetOneDriveDirectLink#10]
文件数量级别大概200-300个；
有时候可以打开（等待一会），有时候一直无法正常打开；

无法正常打开的表现是链接列表无内容，一直现实等待API返回。

**Comment by Mapaler** [comment]
会是网络不好的原因吗，查看一下控制台有没有什么报错。

**Comment by Mapaler** [comment]
![图像 1](https://user-images.githubusercontent.com/6565860/80912580-8080ce00-8d70-11ea-856c-feff8f914d81.png)
我试验了一下文件几百个多选的情况，错误发生在 OneDrive.js 里面，官方 API 不是我能控制的了。

**Comment by zplzpl** [comment]
要多次重试，才可能从api返回接口；而且要刷新整个界面；

**Comment by Mapaler** [comment]
尝试用好的梯子呢？我觉得是因为服务器在中国没有CDN的原因。

**Comment by zplzpl** [comment]
你使用梯子得情况，不会有这种情况吗？我还是会

**Comment by Mapaler** [comment]
不知道呢，反正我的梯子不好。
你就看看控制台的报错，发生地点如果是API里面的我是改不了的，是微软自己的锅。

**Comment by zplzpl** [comment]
ok，感谢你编写的工具
