### ISSUE TITLE
求助大佬，需要用authkey的图片是否有可能让链接末尾是图片的真实后缀

### ISSUE THREAD

**Issue by fengwyue** [Mapaler/GetOneDriveDirectLink#14]
工具很好用，在文章内插入查看都没有问题。
但是WordPress的「自动将文章第一张图片设为特色图片」功能貌似无法使用这种链接格式的图片，会裂。不知道有没有大佬知道是否有解决办法……

**Comment by Mapaler** [comment]
我怀疑不是图片链接的问题，而是不支持302重定向的问题
目前的有认证的 authkey 是必须要作为参数提交的，找不到如何生成无 authkey 的完全公开文件夹的方法了。

**Comment by fengwyue** [comment]
> 我怀疑不是图片链接的问题，而是不支持302重定向的问题 目前的有认证的 authkey 是必须要作为参数提交的，找不到如何生成无 authkey 的完全公开文件夹的方法了。

哈哈乱试解决了。使用「https://storage.live.com/items/${file.id}?authkey=【】&filename=${file.name}」这样的格式就可以了。格式后缀不能在前面，不然好像读取不到authkey参数。感谢大佬的工具！

**Comment by Mapaler** [comment]
还有这么简单的问题啊，说明程序员偷懒没有解析URL，而是直接读取的最右侧内容
