### ISSUE TITLE
多次尝试之后 无法获取文件下载链接

### ISSUE THREAD

**Issue by Hello1999** [Mapaler/GetOneDriveDirectLink#2]
共选择 1 个文件。
![image](https://user-images.githubusercontent.com/25933779/34429955-2609487c-ec9a-11e7-8d10-9ae43c1fbf78.png)
如图显示
完成了操作,,无法获取链接. 
之前试了两个成功了. 之后的就不行了.  
不知道能不能联系上大佬~

**Comment by Mapaler** [comment]
我也不知道哦，毕竟我没遇到过这些特殊情况，你自己排查一下吧。还要检查是不是网络的原因。

**Comment by Hello1999** [comment]
哈哈, 谢谢大佬. 找到原因了. 原来每次获取地址之前 需要去文件分享界面设置一个嵌入HTML的选项,   这样的话 就成功了~~~

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
