### ISSUE TITLE
https://onedrive.gimhoy.com/

### ISSUE THREAD

**Issue by Gravityle** [Mapaler/GetOneDriveDirectLink#3]
这个站点并不需要获取权限即可解析真实地址，看返回的header应该也是用的微软的api，这个和您的有何不同？

**Comment by Mapaler** [comment]
这只是单个文件的地址获取，无法获取文件的详细信息，扩展名都要自己定的。
我一直都是做批量的。
最开始软件版的的做法是填入公开文件夹的分享地址，这样会把整个文件夹的文件直链地址都显示出来。这样确实不需要微软帐号权限，单文件同理。
现在做网页版是觉得那样的选择性还是太少了（无法指定性选择文件，只能获取全部），而且能得到的信息参数太少（只有文件名、id等少数信息）。
所以使用微软SDK直接登录OneDrive自己选择文件，而且可以获得返回的很多数据信息，可以用于书写掩码。

**Comment by Mapaler** [comment]
另外这种单文件型不需要用微软API的，只需要获得一个item ID就行。

**Comment by Gravityle** [comment]
感谢您的耐心解答，另外能否大概说明一下获取item ID的方法，我有很多文件需要获取外链，但是目前这两种对我来说都算是比较笨的人工方式，服务器语言只会一些PHP，感谢~

**Comment by Mapaler** [comment]
如果你有大量数据，建议不要用OneDrive外链，微软检测到异常会封的，我有朋友做音乐外链被封过很多账号。
<hr>

![image 13](https://user-images.githubusercontent.com/6565860/42049557-f03a837c-7b38-11e8-88dc-0603d761052e.png)  
首先获取文件夹id  
然后访问这个文件夹的外联地址  
`https://storage.live.com/items/*ID*`
得到文件夹信息的XML  
![image 14](https://user-images.githubusercontent.com/6565860/42049667-3171aa8c-7b39-11e8-911e-6e02b396cd37.png)  
里面有文件夹下所有文件的id号。

**Comment by Gravityle** [comment]
非常感谢您的建议与耐心解答，我先研究一下，谢谢！
