### ISSUE TITLE
似乎...onedrive.live.com给墙了？

### ISSUE THREAD

**Issue by xuelainiao** [Mapaler/GetOneDriveDirectLink#4]
捂脸，试着安装了一下，然后申请了clienID，测试发现onedrive.live.com打不开的错误，求教

**Comment by Mapaler** [comment]
对啊，onedrive.live.com域名被墙了好多年了。不过直链的域名还没被墙。

**Comment by xuelainiao** [comment]
那这套源码就没法使了呗

**Comment by Mapaler** [comment]
你到底是要用来干什么。用来找直链的话，就是生成的时候需要翻墙，用的时候不需要

**Comment by xuelainiao** [comment]
嗯，已经尝试过了，现在这种方法公开文件夹似乎不好使了
