### ISSUE TITLE
你好 我在找authkey的时候 怎么没有看到 "嵌入"那个按钮呢?

### ISSUE THREAD

**Issue by yutao8** [Mapaler/GetOneDriveDirectLink#6]
请教一下 现在要怎么找到authkey呢

**Comment by Mapaler** [comment]
![screenshot 2018-08-13 12 55 16](https://user-images.githubusercontent.com/6565860/44013462-327e5c62-9ef8-11e8-92cc-6c18633f106b.png)
选中文件夹，就有嵌入了啊

**Comment by yutao8** [comment]
![image](https://user-images.githubusercontent.com/8745770/44013857-dfbf37be-9efa-11e8-80aa-f998b10404ac.png)

我这不一样,难道跟账号有关系?

**Comment by Mapaler** [comment]
是不是office 365和普通的OneDrive不一样？

**Comment by yutao8** [comment]
有可能

**Comment by Mapaler** [comment]
你自己想法找找有没有其他的公开分享方法，然后找链接里面的参数。

**Comment by yutao8** [comment]
好的 谢谢

**Comment by Mapaler** [comment]
找不到吗？

**Comment by yutao8** [comment]
没有呢
