### ISSUE TITLE
发生错误.error

### ISSUE THREAD

**Issue by ghost** [Mapaler/GetOneDriveDirectLink#9]
自行搭建之后,点击`从OneDrive选择文件` 然后出现登录窗口马上闪退.然后报错.
![如图](https://user-images.githubusercontent.com/53611704/73898222-a0186f80-48c3-11ea-8027-84cdefe5c0f1.png)
也没有更多错误信息..

**Comment by Mapaler** [comment]
自行搭建需要注册自己的应用 ID，并在应用ID里填写自己的回调URL，如果回调URL不存在于列表内就会失败。
我只添加了这个地方的ID。
![图像 34](https://user-images.githubusercontent.com/6565860/73926533-c0b7e800-490a-11ea-8ae7-7fb2c3047da2.png)

还需要有申请权限
![图像 35](https://user-images.githubusercontent.com/6565860/73927135-c82bc100-490b-11ea-9ccc-322eaed91f13.png)

**Comment by ghost** [comment]
@Mapaler 没啥问题.我也创建了应用在script更新了ID.权限也给出去了.才出上面的错误.
不过我晚上继续测试发现.具体问题是[这里](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow)
我把`隐式授权`的
-访问令牌
-ID 令牌
勾上就好了.
我上次其实搭建过一次,没记得这两要勾上.可能是我记岔了吧.谢谢作者.

**Comment by Mapaler** [comment]
看来问题是后来出现的，我做这个的时候，还是老的应用中心，没这么多设置选项。我并没有在转移的“Azure 门户应用注册”中新建过。

**Comment by ghost** [comment]
@Mapaler 嗯,现在应用中心关闭了全部在azuru 中注册应用.或许可以在文档加上一下.把`隐式授权`的两个令牌给勾了.这`iss`就关闭吧

**Comment by Mapaler** [comment]
我把掩码改成ES6的原生模板字符串了

**Comment by sengoku-f** [comment]
设置了 `替换URL` 和 `隐式授权`,还是出现 `发生错误.error`

```
0: Error at new e (https://js.live.net/v7.2/OneDrive.js:4:32744) at https://js.live.net/v7.2/OneDrive.js:4:19308
```

**Comment by ghost** [comment]
@sengoku-f  
应该还是老问题.你按照作者写的文档检查步骤是否完整.
另外你创建的这个应用 有没有在 "证书和密码 "里面生成一个 `客户端密码` .虽然本项目里面不需要用到这个密码.但是这个步骤是必要的.
另外"身份验证"里面的`允许公共客户端流`也打开试试.

**Comment by sengoku-f** [comment]
> @sengoku-f
> 应该还是老问题.你按照作者写的文档检查步骤是否完整.
> 另外你创建的这个应用 有没有在 "证书和密码 "里面生成一个 `客户端密码` .虽然本项目里面不需要用到这个密码.但是这个步骤是必要的.
> 另外"身份验证"里面的`允许公共客户端流`也打开试试.

试过了,`客户端密码` 和 `允许公共客户端流` 已配置,还是不行

**Comment by Mapaler** [comment]
我看了下我的，没有密码，也没有勾`允许公共客户端流`

**Comment by sengoku-f** [comment]
解决了
创建应用的时候需要选择`任何组织目录(任何 Azure AD 目录 - 多租户)中的帐户和个人 Microsoft 帐户(例如，Skype、Xbox)`
不能选择默认的`个人 Microsoft 帐户(例如，Skype、Xbox)`

**Comment by sengoku-f** [comment]
另外想问一下大佬,有办法让直链直接在浏览器里预览吗,现在获得的都是直接下载文件

**Comment by Mapaler** [comment]
`http://storage.live.com/items/${file.id}:/${file.name}`域名跳转的就是可以在浏览器预览的，如果你的不行，可以检查是否是浏览器本身强制修改了mmie的问题。

新增的 1drv.ws 方式，获取的是下载链接，`content-Dispositong` 值为 `attachemen`，所以只能是下载。
1drv.ws 方式我并不推荐，但是相对更傻瓜一点，所以加上了。
